[build]
  base = "client"
  publish = "client/dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-server.herokuapp.com/api/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
